### ISSUE TITLE
Slow invocation?

### ISSUE THREAD

**Issue by ulneva** [JuliaOpt/AmplNLWriter.jl#20] opened 2015-11-17 18:38 UTC
I am trying AmplNKWriter with Knitro. The code is working reasonably fast with JuMP+Knitro (Knitro is called within seconds, problem is solved in around 300 sec), however when AmplNLWriter is used, I have been waiting for 25 minutes, but I do not see any signs of knitroampl being invoked, while the physical memory usage almost tripled compared to JuMP+Knitro. Any suggestions? The code is attached. Thank you!
[TestOptProblem9_2.txt](https://github.com/JuliaOpt/AmplNLWriter.jl/files/37047/TestOptProblem9_2.txt)

**Comment by adowling2** [comment] 2017-04-19 01:14
I am having similar issues with AmplNLWriter and SCIP.

**Comment by mlubin** [comment] 2017-04-19 01:23
Any reason why you prefer AmplNLWriter over [SCIP.jl](https://github.com/SCIP-Interfaces/SCIP.jl)?

**Comment by adowling2** [comment] 2017-04-19 01:32
I am having trouble getting SCIP.jl to work for this problem (and some variants). I have initialization code before the solve statement to ensure the initial point is feasible. (Which I check with [DegeneracyHunter.jl](https://github.com/adowling2/DegeneracyHunter.jl)). When I use AmplNLWriter.jl for another variant of this model, SCIP says the initial point is feasible and the pre-solve takes ~10 seconds. For the same problem variant, however, SCIP.jl says the initial point is infeasible and pre-solve takes > 1 hour. SCIP tells me which equation is infeasible, but I don't believe it. I am trying to get a reproducible smaller example, which I'll post as an issue to SCIP.jl.

**Comment by adowling2** [comment] 2017-04-21 16:19
@mlubin I reported the issue described above as [bug in SCIP.jl](https://github.com/SCIP-Interfaces/SCIP.jl/issues/49).

I dug into the issue above more. It turns out the MINLP is too large. SCIP uses more than 150GB of memory while loading the problem. The OS then kills scipampl, hence the missing solution file.

**Comment by odow** [comment] 2017-11-24 01:29
Closing as other than being slow, this doesn't appear to be a problem with AmplNLWriter. We also have a better error message for the second issue.

**Closed by odow** 2017-11-24 01:29 UTC
Labels: fixed in PR
