### ISSUE TITLE
Error with LazyList when using AmplNLSolver in JuMP

### ISSUE THREAD

**Issue by mathtd** [JuliaOpt/AmplNLWriter.jl#39] opened 2016-06-15 19:26 UTC
I'm using Knitro through AMPL:

`model = Model(solver=AmplNLSolver("/Applications/ampl/knitro"))
`

The error comes from the following (simplified) constraint 

`@NLconstraint(model, constraint[j=1:n], a <= (sum{A[i]^a , i=find(Ω[:,j].==1)})
`

I get the error:

`ERROR: LoadError: MethodError: `^` has no method matching ^(::Lazy.LazyList, ::Float64)`

This does not happen when instead of using AMPL I use IPopt directly through IpoptSolver().

**Comment by JackDunnNZ** [comment] 2016-06-15 20:00
Can you add definitions of `a`, `A`, and `Ω` that will let me reproduce this so I can look into it?

**Comment by mathtd** [comment] 2016-06-15 20:25
Here's the replication code

```
using JuMP
using AmplNLWriter

model_num = Model(solver=AmplNLSolver("/Applications/amplide.macosx64/knitro",["outlev=1","par_numthreads=4"]))

n = 1000
srand(1)
@variable(model_num, r[i=1:n] >= 0)

Ω = round(Int64,rand(n,n).<1/n*5)

@NLconstraint(model_num, techno_constraint[j=1:n], r[j] <= (sum{1/n , i=find(Ω[:,j].==1)}))
@NLobjective(model_num, Min, (sum{r[j], j=1:n}))

solve(model_num)
```

It seems to only happen when n is large, like 1000. For n=10 there is no problem.

**Comment by JackDunnNZ** [comment] 2016-06-16 01:40
This error is happening whenever the `sum{}` iterates over an empty set. The following is a minimal working example:

```
using JuMP
using AmplNLWriter

m = Model(solver=IpoptNLSolver())
@variable(m, x)
@NLconstraint(m, x <= sum{0, j = []})
solve(m)
```

@mlubin Should I be handling this case here, or is it something that should be changed before the expressions get to AmplNLWriter? The expression that comes through in the above example is `:(x[1] - (+)())`

**Comment by mlubin** [comment] 2016-06-16 01:45
Well, a sum of zero things is zero, so the expression isn't garbage at least. How hard would it be for you to handle?

**Comment by JackDunnNZ** [comment] 2016-06-16 01:47
It shouldn't be much, just wanted to check it makes sense to do it here. FWIW CoinOptServices crashes on the same thing:

```
julia> solve(m)
ERROR: Do not know how to handle :call expression (+)() with fewer than 2 args
 in error at error.jl:22
 in expr2osnl! at /Users/jack/.julia/v0.4/CoinOptServices/src/translations.jl:151
 in binary2osnl! at /Users/jack/.julia/v0.4/CoinOptServices/src/translations.jl:251
 in expr2osnl! at /Users/jack/.julia/v0.4/CoinOptServices/src/translations.jl:158
 in loadproblem! at /Users/jack/.julia/v0.4/CoinOptServices/src/CoinOptServices.jl:359
 in _buildInternalModel_nlp at /Users/jack/.julia/v0.4/JuMP/src/nlp.jl:1210
 in build at /Users/jack/.julia/v0.4/JuMP/src/solvers.jl:315
 in solve at /Users/jack/.julia/v0.4/JuMP/src/solvers.jl:134
```

**Comment by mlubin** [comment] 2016-08-03 19:07
I think I just ran into a similar issue:
```jl
import Convex
using ConicNonlinearBridge, AmplNLWriter

x = Convex.Variable(1,:Int)
y = Convex.Variable(1)

problem = Convex.minimize(-3x - y,
                   x >= 1,
                   y >= 0,
                   3x + 2y <= 10,
                   x^2 <= 5,
                   exp(y) + x <= 7)
Convex.solve!(problem, ConicNLPWrapper(nlp_solver=BonminNLSolver()))
```
gives
```
ERROR: LoadError: MethodError: `+` has no method matching +(::Float64, ::Lazy.LazyList)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...)
  +(::AbstractFloat, !Matched::Bool)
  +(::Float64, !Matched::Float64)
  ...
 in add_tree_to_constr! at /home/mlubin/.julia/v0.4/AmplNLWriter/src/nl_linearity.jl:235
 in add_linear_tree! at /home/mlubin/.julia/v0.4/AmplNLWriter/src/nl_linearity.jl:176
 in prune_linear_terms! at /home/mlubin/.julia/v0.4/AmplNLWriter/src/nl_linearity.jl:134
 in process_expression! at /home/mlubin/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:399
 in anonymous at /home/mlubin/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:205
 in map_to! at abstractarray.jl:1286
 in map at ./abstractarray.jl:1308
 in loadproblem! at /home/mlubin/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:181
 in _buildInternalModel_nlp at /home/mlubin/.julia/v0.4/JuMP/src/nlp.jl:1211
 in build at /home/mlubin/.julia/v0.4/JuMP/src/solvers.jl:315
 in solve at /home/mlubin/.julia/v0.4/JuMP/src/solvers.jl:134
 in optimize! at /home/mlubin/.julia/v0.4/ConicNonlinearBridge/src/nonlinear_to_conic.jl:180
 in solve! at /home/mlubin/.julia/v0.4/Convex/src/solution.jl:34
 in solve! at /home/mlubin/.julia/v0.4/Convex/src/solution.jl:13
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
```

**Comment by JackDunnNZ** [comment] 2016-08-04 22:32
Looks like it. Did we decide if it's something we want to handle at the AmplNLWriter level (and presumably again in CoinOptServices too)? If so I'll fix it.

**Comment by mlubin** [comment] 2016-08-04 23:26
Just took a look and it seems easy to fix on the JuMP side.

**Comment by JackDunnNZ** [comment] 2016-08-05 02:25
Fixed by JuliaOpt/JuMP.jl#820 and #41

**Closed by JackDunnNZ** 2016-08-05 02:25 UTC
